### ISSUE TITLE
Advance Audit Trails odoo_v13: Need to improve some text in README.md file

### ISSUE THREAD

**Issue by ketanserpentcs** [ketanserpentcs/Project-Issue#1]
Need to improve some text in README.md file

**Steps to Replicate:**
1) Goto source folder
2) Open the README.md file
3) Observe it

Please check below portion and improve it

**OCA Dependencies:
----------------------------------------------------
https://apps.odoo.com/apps/modules/12.0/auditlog/**

It's should be displayed :

**OCA Dependencies:
----------------------------------------------------
https://apps.odoo.com/apps/modules/13.0/auditlog/**

![readme_file](https://user-images.githubusercontent.com/22834304/86085476-e2358e00-babc-11ea-887d-179ebcd34573.png)

![readme_file](https://user-images.githubusercontent.com/22834304/86085533-01342000-babd-11ea-9825-d4780a6cde1d.png)

**Comment by YogendrasinhChavda** [comment]
Hello @ketanserpentcs sir,
As i checked in our gitlab branch there is already 13.0 in README.md file.  I thought by mistake you took the v12.0 files for screenshot.
Please see the below screenshots for more details.
ssh://gitlab@202.131.126.142:4446/yogendra/advance_audit_trail.git

![advance_audit_log_v13_resolve](https://user-images.githubusercontent.com/11770935/86106721-88de5680-bade-11ea-8587-b470a085cfea.png)


![advance_audit_log_resolve_02](https://user-images.githubusercontent.com/11770935/86106730-8d0a7400-bade-11ea-8fa6-3b8721ac0bcd.png)

Thanks.

**Comment by ketanserpentcs** [comment]
@YogendrasinhChavda ,

Issue has been closed as per developer comment.
